### ISSUE TITLE
Provided migrations are broken

### ISSUE THREAD

**Issue by nicorikken** [freedomvote/freedomvote#68]
**provided migrations are broken**

In trying to apply the provided migrations on the database, a conflict occurs.
```
$ python manage.py syncdb
/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

CommandError: Conflicting migrations detected (0004_auto_20161219_0855, 0007_auto_20161216_1433 in core).
To fix them run 'python manage.py makemigrations --merge'
$ python manage.py makemigrations --merge
Merging core
  Branch 0004_auto_20161219_0855
    - Remove field type from link
    - Add field name_en to category
    - Add field name_nl to category
    - Add field name_en to party
    - Add field name_nl to party
    - Add field shortname_en to party
    - Add field shortname_nl to party
    - Add field description_en to question
    - Add field description_nl to question
    - Add field text_en to question
    - Add field text_nl to question
    - Add field name_en to state
    - Add field name_nl to state
    - Remove field state from politician
    - Add field state to politician
    - Delete model LinkType
  Branch 0007_auto_20161216_1433
    - Add field name_en to category
    - Add field name_nl to category
    - Add field name_en to linktype
    - Add field name_nl to linktype
    - Add field name_en to party
    - Add field name_nl to party
    - Add field shortname_en to party
    - Add field shortname_nl to party
    - Add field description_en to question
    - Add field description_nl to question
    - Add field text_en to question
    - Add field text_nl to question
    - Add field name_en to state
    - Add field name_nl to state
    - Remove field state from politician
    - Add field state to politician
    - Alter field state on politician
    - Add field color to party
    - Remove field color from party
    - Add field background_color to party
    - Add field font_color to party

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /home/freedomvote/freedomvote/app/core/migrations/0008_merge.py
$ python manage.py syncdb
/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py:24: RemovedInDjango19Warning: The syncdb command will be removed in Django 1.9
  warnings.warn("The syncdb command will be removed in Django 1.9", RemovedInDjango19Warning)

Operations to perform:
  Synchronize unmigrated apps: django_admin_bootstrapped, staticfiles, messages, modeltranslation, piwik, djangocms_admin_style, meta, sekizai, colorfield, treebeard
  Apply all migrations: core, sessions, admin, sites, auth, menus, contenttypes, cms, easy_thumbnails, djangocms_text_ckeditor
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying sites.0001_initial... OK
  Applying cms.0001_initial... OK
  Applying cms.0002_auto_20140816_1918... OK
  Applying cms.0003_auto_20140926_2347... OK
  Applying cms.0004_auto_20140924_1038... OK
  Applying cms.0005_auto_20140924_1039... OK
  Applying cms.0006_auto_20140924_1110... OK
  Applying cms.0007_auto_20141028_1559... OK
  Applying cms.0008_auto_20150208_2149... OK
  Applying cms.0008_auto_20150121_0059... OK
  Applying cms.0009_merge... OK
  Applying cms.0010_migrate_use_structure... OK
  Applying cms.0011_auto_20150419_1006... OK
  Applying cms.0012_auto_20150607_2207... OK
  Applying cms.0013_urlconfrevision... OK
  Applying core.0001_initial... OK
  Applying core.add_core_statistic_indexes... OK
  Applying core.rename_core_politician_unique_url... OK
  Applying core.0002_auto_20150401_0929... OK
  Applying core.0003_auto_20150521_0856... OK
  Applying core.0004_politician_user... OK
  Applying core.migrate_party_user... OK
  Applying core.0001_auto_20150727_1227... OK
  Applying core.0002_auto_20150824_1250... OK
  Applying core.0003_auto_20160106_0925... OK
  Applying core.0004_auto_20161214_1255... OK
  Applying core.0005_auto_20161216_1206... OK
  Applying core.0006_party_color... OK
  Applying core.0007_auto_20161216_1433... OK
  Applying core.0004_auto_20161219_0855...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 25, in handle
    call_command("migrate", **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 221, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 147, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 62, in database_forwards
    field,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 399, in add_field
    self.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 107, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "name_en" of relation "core_category" already exists
```

So the root of the conflict seems to be in `column "name_en" of relation "core_category" already exists`.

Clearing the `migrations/` directory, running `python manage.py makemigrations` and `python manage.py syncdb` worked flawless, to work around the issue.

*Perhaps I'm doing the wrong things here, but I got the sense there is no error in applying migrations on an initial deploy*

**Comment by nicorikken** [comment]
Going by the checked in migrations, this is the current tree of migrations:

```
x- 0001_initial
\- add_core_statistic_indexes
 \- rename_core_politician_unique_url
  \- 0002_auto_20150401_0929
   \- 0003_auto_20150521_0856
    \- 0004_politician_user
x- 0001_auto_20150727_1227
\- 0002_auto_20150824_1250
 \- 0003_auto_20160106_0925
  |- 0004_auto_20161214_1255
  |\- 0005_auto_20161216_1206
  | \- 0006_party_color
  |  \- 0007_auto_20161216_1433
  \- 0004_auto_20161219_0855
```

**Comment by nicorikken** [comment]
It seems the `0004..._0855` migration supersedes the `0004..._1255` migration, as it includes changes to the linktype. I'll try to remove them, to see how it differs.

**Comment by nicorikken** [comment]
I hope this commit will fix it: https://github.com/nicorikken/freedomvote/commit/c0fb8ebe150c979b97239c8fcd3cffc93e03ee48

**Comment by nicorikken** [comment]
I've successfully transfered the URL change towards the `settings.ini` file in the Ansible configuration, such that I could create the clean pull request #69
